version: '3.3'

services:
    mongodb:
        image: mongo:latest
        restart: always

    hypercane:
        depends_on:
            - mongodb
        image: oduwsdl/hypercane:latest
        build: ./
        command: bash
        restart: always
        volumes:
            - .:/hypercane-work
        stdin_open: true
        environment:
            - HC_CACHE_STORAGE=mongodb://mongodb/csHC
